# Generated by Django 3.2.7 on 2021-09-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfumeResult',
        ),
    ]
